### ISSUE TITLE
Error) Unescaped left brace in regex is illegal here in regex

### ISSUE THREAD

**Issue by zzong2006** [hghodrati/wikifil#1]
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/{{ <-- HERE [^}]*}}/ at wikifil.pl line 34.

delete the single line below makes works like a charm.

```
s/{{[^}]*}}//g;         # remove {{icons}} and {tables}
```

**Comment by euzero** [comment]
The code seems to have one bug located at line 34. It might be better to change it to 's/{{[^}]*}}//g; # remove {{icons}} and {tables}'

**Comment by euzero** [comment]
The code seems to have one bug located at line 34. It might be better to change it to 's/\{\{[^}]*\}\}//g;     # remove {{icons}} and {tables}'

**Comment by euzero** [comment]
The code seems to have one bug located at line 34. It might be better to change it to 's/\{\{[^}]*\}\}//g;     # remove {{icons}} and {tables}}'

**Comment by euzero** [comment]
The code seems to have one bug located at line 34. It might be better to change it to 's/\{\{[^}]*\}\}//g;     # remove {{icons}} and {tables}'

**Comment by euzero** [comment]
The code seems to have one bug located at line 34. It might be better to change it to
`s/\{\{[^}]*\}\}//g;     # remove {{icons}} and {tables}
`
